name: "build-test"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install nix
        uses: cachix/install-nix-action@v26

      - name: Run generate-nix-hash action
        uses: ./
        with:
          rev: v27.0 # initial commit
          owner: Groestlcoin
          repo: groestlcoin
          file: config.json

      - name: Verify results
        run: |
          cat > expected.json <<EOF
          {
            "rev": "v27.0",
            "sha256": "0f6vi2k5xvjrhiazfjcd4aj246dfcg51xsnqb9wdjl41cg0ckwmf"
          }
          EOF

          diff config.json expected.json
