name: "build-test"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12

      - name: Run generate-nix-hash action
        uses: ./
        with:
          rev: v26.0 # initial commit
          owner: Groestlcoin
          repo: groestlcoin
          file: config.json

      - name: Verify results
        run: |
          cat > expected.json <<EOF
          {
            "rev": "v26.0",
            "sha256": "00qvaf53jszsk1rr029zmq60v8w0r92192ab65k2krkmh7ybla9l"
          }
          EOF

          diff config.json expected.json
