name: "build-test"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12

      - name: Run generate-nix-hash action
        uses: ./
        with:
          rev: v0.21.13 # initial commit
          owner: bitcoin-ABC
          repo: bitcoin-abc
          file: config.json

      - name: Verify results
        run: |
          cat > expected.json <<EOF
          {
            "rev": "0.21.13",
            "sha256": "1s0qrrin8ry9klvjaxj4hd3qlf3cayfisq8pn7idqddgcg0lc079"
          }
          EOF

          diff config.json expected.json
