name: "build-test"
on:
  pull_request:
  push:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install nix
        uses: cachix/install-nix-action@v12

      - name: Run generate-nix-hash action
        uses: ./
        with:
          file: config.json

      - name: Verify results
        run: |
          cat > expected.json <<EOF
          {
            "sha256": "1cnzqhmzlca07frkiay0dkdw2f0gcf6abn0c9ymq0x65171pj689"
          }
          EOF

          diff config.json expected.json
